version: '3.8'

services:
  # 开发环境
  vehicle-maintenance-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vehicle-maintenance-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - vehicle-maintenance-dev-network
    command: npm run dev

networks:
  vehicle-maintenance-dev-network:
    driver: bridge