version: '3.8'

services:
  # 车辆保养记录系统
  vehicle-maintenance:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-maintenance-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # 可选：挂载nginx日志到主机
      - ./logs/nginx:/var/log/nginx
    networks:
      - vehicle-maintenance-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加反向代理（如果需要HTTPS或多域名支持）
  nginx-proxy:
    image: nginx:alpine
    container_name: vehicle-maintenance-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro
    depends_on:
      - vehicle-maintenance
    networks:
      - vehicle-maintenance-network
    profiles:
      - proxy
    restart: unless-stopped

networks:
  vehicle-maintenance-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local