name = "vehicle-maintenance"
compatibility_date = "2024-01-01"

[env.production]
name = "vehicle-maintenance-prod"

[env.staging]
name = "vehicle-maintenance-staging"

# Pages 项目配置
[pages]
build_command = "npm run build"
build_output_dir = "dist"